import React, { useState } from 'react';

const WorkOrderUploader = () => {
    const [fileData, setFileData] = useState(null);
    const [status, setStatus] = useState({ loading: false, message: '', type: '' });

    // 1. Handle File Selection and Parsing
    const handleFileChange = (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
            try {
                const json = JSON.parse(event.target.result);
                setFileData(json);
                setStatus({ 
                    loading: false, 
                    message: `File loaded: ${json.length} Work Orders detected.`, 
                    type: 'success' 
                });
            } catch (err) {
                setStatus({ 
                    loading: false, 
                    message: "Invalid JSON file. Please check the file format.", 
                    type: 'error' 
                });
            }
        };
        reader.readAsText(file);
    };

    // 2. Handle API Call to Node.js
    const handleUpload = async () => {
        if (!fileData) return;

        setStatus({ loading: true, message: 'Uploading to server...', type: 'info' });

        try {
            const response = await fetch('http://localhost:8002/part/uploadWorkOrders', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(fileData),
            });

            const result = await response.json();

            if (response.ok) {
                setStatus({ 
                    loading: false, 
                    message: `Success! ${result.recordsProcessed} Work Orders synced to database.`, 
                    type: 'success' 
                });
                setFileData(null); // Clear after success
            } else {
                throw new Error(result.error || 'Upload failed');
            }
        } catch (err) {
            setStatus({ 
                loading: false, 
                message: `Error: ${err.message}`, 
                type: 'error' 
            });
        }
    };

    return (
        <div style={{ padding: '20px', maxWidth: '600px', margin: 'auto', border: '1px solid #ddd', borderRadius: '8px' }}>
            <h2>PM Work Order Uploader</h2>
            <p>Select the <strong>extracted_work_orders.json</strong> file generated by the Python script.</p>

            <div style={{ marginBottom: '20px' }}>
                <input 
                    type="file" 
                    accept=".json" 
                    onChange={handleFileChange} 
                    disabled={status.loading}
                />
            </div>

            {status.message && (
                <div style={{ 
                    padding: '10px', 
                    marginBottom: '20px', 
                    borderRadius: '4px',
                    backgroundColor: status.type === 'error' ? '#fee2e2' : '#dcfce7',
                    color: status.type === 'error' ? '#991b1b' : '#166534'
                }}>
                    {status.message}
                </div>
            )}

            <button 
                onClick={handleUpload} 
                disabled={!fileData || status.loading}
                style={{
                    padding: '10px 20px',
                    backgroundColor: !fileData || status.loading ? '#ccc' : '#2563eb',
                    color: 'white',
                    border: 'none',
                    borderRadius: '4px',
                    cursor: !fileData || status.loading ? 'not-allowed' : 'pointer'
                }}
            >
                {status.loading ? 'Processing...' : 'Sync to Database'}
            </button>
        </div>
    );
};

export default WorkOrderUploader;